### ISSUE TITLE
Is this utility supported/been tested on Mac (pyside errors)?

### ISSUE THREAD

**Issue by firstkingofrome** [SeismicData/asdf_sextant#8]
Hello, I tried running this on Mac (intel running 11.4), I set it up by running the following commands:

conda create -n "asdfSextant" python=3.8 ipython pyasdf pyside2
conda activate asdfSextant
pip install asdf-sextant

When I run asdf-sextant I get an error (NameError: name '_init_pyside_extension' is not defined). Any idea what might be causing this?

Thank You, I appreciate any assistance,

Full Output:

Traceback (most recent call last):
  File "/Users/eckert/anaconda3/envs/asdfSextant/bin/asdf-sextant", line 5, in <module>
    from asdf_sextant.main import launch
  File "/Users/eckert/anaconda3/envs/asdfSextant/lib/python3.8/site-packages/asdf_sextant/main.py", line 11, in <module>
    from PySide2 import QtGui, QtCore
  File "/Users/eckert/anaconda3/envs/asdfSextant/lib/python3.8/site-packages/PySide2/__init__.py", line 107, in <module>
    _setupQtDirectories()
  File "/Users/eckert/anaconda3/envs/asdfSextant/lib/python3.8/site-packages/PySide2/__init__.py", line 58, in _setupQtDirectories
    import shiboken2
  File "/Users/eckert/anaconda3/envs/asdfSextant/lib/python3.8/site-packages/shiboken2/__init__.py", line 30, in <module>
    _init_pyside_extension()
NameError: name '_init_pyside_extension' is not defined

**Comment by NNovoa-CDWR** [comment]
I encountered the same error running on a Windows 2019 Server with Conda. Has anyone found a solution to this?
