### ISSUE TITLE
running asdf-sextant

### ISSUE THREAD

**Issue by hadigh** [SeismicData/asdf_sextant#9]
Hello

I have installed the GUI on an Ubuntu machine following the instructions which went OK. Running asdf-sextant from terminal produces the below error message. I would appreciate any help on this matter :)

Traceback (most recent call last):
  File "/home/hadi/miniconda/envs/obspy/bin/asdf-sextant", line 5, in <module>
    from asdf_sextant.main import launch
  File "/home/hadi/miniconda/envs/obspy/lib/python3.7/site-packages/asdf_sextant/main.py", line 32, in <module>
    from . import asdf_sextant_window
  File "/home/hadi/miniconda/envs/obspy/lib/python3.7/site-packages/asdf_sextant/asdf_sextant_window.py", line 44, in <module>
    from .svg_graphics_view import SvgGraphicsView
  File "/home/hadi/miniconda/envs/obspy/lib/python3.7/site-packages/asdf_sextant/svg_graphics_view.py", line 4, in <module>
    class SvgGraphicsView(QtGui.QGraphicsView):
AttributeError: module 'PySide2.QtGui' has no attribute 'QGraphicsView'

**Comment by gferragu** [comment]
Hey @hadigh, did you ever get this worked out? I just ran into the same issue and fixed it by installing `pyqtgraph=0.11.0rc0` and then downgrading the conda environment to `python=3.7`

**Comment by hadigh** [comment]
@gferragu , Thanks a lot! indeed your suggestion fixed the problem :)
